create table if not exists public.waitlist_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  city text,
  role text not null check (role in ('general', 'golfer', 'coach', 'facility')),
  source text not null default 'unknown',
  facility_name text,
  created_at timestamptz not null default now()
);

alter table public.waitlist_submissions add column if not exists source text;
update public.waitlist_submissions set source = 'unknown' where source is null;
alter table public.waitlist_submissions alter column source set default 'unknown';
alter table public.waitlist_submissions alter column source set not null;
alter table public.waitlist_submissions alter column email drop not null;

alter table public.waitlist_submissions enable row level security;

drop policy if exists "Allow public waitlist submissions" on public.waitlist_submissions;
create policy "Allow public waitlist submissions"
on public.waitlist_submissions
for insert
to anon, authenticated
with check (true);
